from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Optional
import uvicorn
import os
from docx import Document

app = FastAPI(title="CAM Generator Service", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve generated files
os.makedirs("output", exist_ok=True)
app.mount("/static", StaticFiles(directory="output"), name="static")

class CamRequest(BaseModel):
    company_data: Optional[dict] = {}
    risk_analysis: Optional[dict] = {}

@app.get("/health")
def health_check():
    return {"status": "ok", "service": "cam-generator", "version": "0.1"}

@app.post("/generate")
def generate_cam(req: CamRequest):
    """
    Generate Credit Appraisal Memo (DOCX).
    Phase 1: Creates a structured template-based document.
    """
    company = req.company_data or {}
    risk = req.risk_analysis or {}
    company_name = company.get("name", "Unknown Company")

    # Generate DOCX
    doc = Document()

    # Title
    doc.add_heading("CREDIT APPRAISAL MEMORANDUM", 0)
    doc.add_paragraph(f"Prepared for: {company_name}")
    doc.add_paragraph(f"GSTIN: {company.get('gstin', 'N/A')}")
    doc.add_paragraph(f"PAN: {company.get('pan', 'N/A')}")
    doc.add_paragraph("─" * 50)

    # Executive Summary
    doc.add_heading("1. Executive Summary", level=1)
    score = risk.get("score", risk.get("final_score", "N/A"))
    grade = risk.get("grade", risk.get("decision", "N/A"))
    doc.add_paragraph(f"Risk Score: {score}/100")
    doc.add_paragraph(f"Risk Grade: {grade}")
    doc.add_paragraph(
        f"Recommendation: {'Approve with standard conditions' if str(score).isdigit() and int(str(score)) >= 70 else 'Review required — enhanced due diligence recommended'}"
    )

    # Five Cs Assessment
    doc.add_heading("2. Five Cs of Credit Assessment", level=1)

    five_cs = {
        "Character": "Stable — promoter track record is clean with no defaults in last 5 years. CIBIL score indicates good repayment history.",
        "Capacity": f"Adequate — Debt Service Coverage Ratio (DSCR) of 1.85x indicates strong ability to meet debt obligations. Current ratio at 1.5x.",
        "Capital": f"Moderate — Net worth of ₹4,00,00,000. Debt-equity ratio at 2.0x is within acceptable limits for the sector.",
        "Collateral": "Partial — Primary security offered includes hypothecation of stock and book debts. Additional collateral may be required for limits above ₹2.5Cr.",
        "Conditions": "Watchlist — Sector is under regulatory review. RBI has flagged concerns about unsecured lending growth in this segment.",
    }

    for c_name, c_detail in five_cs.items():
        doc.add_heading(c_name, level=2)
        doc.add_paragraph(c_detail)

    # Risk Drivers
    doc.add_heading("3. Risk Factor Analysis", level=1)
    drivers = risk.get("drivers", [])
    if drivers:
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        hdr = table.rows[0].cells
        hdr[0].text = "Factor"
        hdr[1].text = "Impact"
        hdr[2].text = "Reason"
        for d in drivers:
            row = table.add_row().cells
            row[0].text = str(d.get("factor", ""))
            impact = d.get("impact", 0)
            row[1].text = f"+{impact}" if impact > 0 else str(impact)
            row[2].text = str(d.get("reason", ""))
    else:
        doc.add_paragraph("No detailed drivers available — stub analysis.")

    # Recommended Terms
    doc.add_heading("4. Recommended Terms", level=1)
    doc.add_paragraph(f"Recommended Credit Limit: ₹{risk.get('recommendedLimit', 'N/A'):,}" if isinstance(risk.get("recommendedLimit"), (int, float)) else f"Recommended Credit Limit: {risk.get('recommendedLimit', 'N/A')}")
    doc.add_paragraph(f"Suggested Interest Rate: {risk.get('suggestedInterestRate', 'N/A')}")

    # Disclaimer
    doc.add_heading("5. Disclaimer", level=1)
    doc.add_paragraph(
        "This Credit Appraisal Memo is generated by the Intelli-Credit AI Engine (Phase 1 — Stub). "
        "The analysis is based on mock data and should not be used for actual credit decisions. "
        "Final credit approval must follow the bank's standard underwriting process."
    )

    # Save
    os.makedirs("output", exist_ok=True)
    filename = f"CAM_{company_name.replace(' ', '_')}.docx"
    filepath = os.path.join("output", filename)
    doc.save(filepath)

    return {
        "camUrl": f"/static/{filename}",
        "summary": {
            "fiveCs": {
                "character": "Stable — clean promoter history",
                "capacity": "Adequate — DSCR 1.85x",
                "capital": "Moderate — net worth ₹4Cr",
                "collateral": "Partial — primary security offered",
                "conditions": "Watchlist — sector under review",
            },
            "recommendation": "PROVISIONAL APPROVAL — final decision pending full risk engine integration",
        },
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8004)
